# Generated by Django 4.2.2 on 2023-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0005_remove_user_is_admin_remove_user_is_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Is student'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Is teacher'),
        ),
    ]
