# Generated by Django 4.2.2 on 2023-06-12 22:42

import Learning.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0009_rename_is_customer_user_is_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=5000, null=True)),
                ('video', models.FileField(upload_to='video/%y', validators=[Learning.validators.file_size])),
            ],
        ),
    ]
